sudo: required
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-add-repository -y "ppa:george-edison55/precise-backports"
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake cmake-data mpi-default-bin mpi-default-dev libjpeg-dev libpng12-dev

before_script:
  - mkdir build
  - cd build
  - cmake ../src -DTESTING=on

script:
  - make
  - make test ARGS=-VV
