name: CI
on: 
  push:
    branches:
      - master
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  style_tests:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
         - { test: whitespace }
         - { test: permissions }

    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyyaml
          apt install -y ninja-build
      - uses: actions/checkout@master
      - name: Configure
        run: |
          cmake -B build -G Ninja -D Python3_EXECUTABLE=$(which python) -S cmake
      - name: Test for ${{ matrix.config.test }}
        run: cmake --build build --target check-${{ matrix.config.test }}

  unit_tests:
    continue-on-error: true
    strategy:
      matrix:
        config:
         # unittest
         - { os: ubuntu18.04, build: cmake_mpi_openmp_smallsmall_shared }
         - { os: ubuntu18.04, build: cmake_mpi_openmp_smallbig_shared }
         - { os: ubuntu18.04, build: cmake_mpi_openmp_bigbig_shared }
    runs-on: ubuntu-latest
    container: "lammps/buildenv:${{ matrix.config.os }}"
    env:
      CCACHE_HASH: ccache-${{ matrix.config.os }}-${{ matrix.config.build }}
      LAMMPS_COMPILE_NPROC: 2
      LAMMPS_CI_RUNNER: github
      LAMMPS_DIR: ${{ github.workspace }}
      LAMMPS_TESTING_DIR: ${{ github.workspace }}/lammps-testing
    steps:
      - name: Get time
        id: time
        run: echo "::set-output name=time::$(date +%s)"
      - uses: actions/checkout@master
      - name: Install Deps
        uses: actions/checkout@master
        with:
          repository: 'lammps/lammps-testing'
          ref: 'master'
          path: 'lammps-testing'
      - uses: actions/cache@v2
        with:
          path: .ccache
          key: ${{ env.CCACHE_HASH }}-${{ steps.time.outputs.time }}
          restore-keys: ${{ env.CCACHE_HASH }}
      - name: Build
        shell: bash -el {0}
        run: |
          ccache -z
          lammps-testing/scripts/unit_tests/${{ matrix.config.build }}/build.sh
          ccache -s
      - name: Test
        shell: bash -el {0}
        run: |
          lammps-testing/scripts/unit_tests/${{ matrix.config.build }}/test.sh
      - name: Upload coverage repos to codecov.io
        uses: codecov/codecov-action@v1
        with:
          file: build/coverage.xml
          flags: unittests

#  compilation_tests:
#    continue-on-error: true
#    strategy:
#      matrix:
#        config:
#         # Ubuntu
#         - { os: ubuntu18.04,    build: cmake_kokkos_mpi_openmp_clang_shared }
#         - { os: ubuntu18.04,    build: cmake_mpi_openmp_bigbig_static }
#         - { os: ubuntu18.04,    build: legacy_mpi_bigbig_shared }
#         - { os: ubuntu18.04,    build: legacy_serial_openmp_smallsmall_static }
#         # Fedora 32
#         - { os: fedora32_mingw, build: cmake_kokkos_mpi_openmp_clang_shared }
#         - { os: fedora32_mingw, build: cmake_serial_smallsmall_static }
#         - { os: fedora32_mingw, build: cmake_mpi_smallbig_shared }
#         - { os: fedora32_mingw, build: legacy_mpi_bigbig_shared }
#         # CentOS 7
#         - { os: centos7,        build: cmake_mpi_openmp_bigbig_static }
#         - { os: centos7,        build: cmake_serial_smallsmall_static }
#         - { os: centos7,        build: cmake_mpi_smallbig_shared }
#         - { os: centos7,        build: legacy_serial_openmp_smallsmall_static }
#         # Windows (MinGW)
#         - { os: fedora32_mingw, build: cmake_mpi_openmp_smallbig_shared_win64 }
#         - { os: fedora32_mingw, build: cmake_serial_smallsmall_static_win32 }
#    runs-on: ubuntu-latest
#    container: "lammps/buildenv:${{ matrix.config.os }}"
#    env:
#      CCACHE_HASH: ccache-${{ matrix.config.os }}-${{ matrix.config.build }}
#      LAMMPS_COMPILE_NPROC: 2
#      LAMMPS_CI_RUNNER: github
#      LAMMPS_DIR: ${{ github.workspace }}
#      LAMMPS_TESTING_DIR: ${{ github.workspace }}/lammps-testing
#    steps:
#      - name: Get time
#        id: time
#        run: echo "::set-output name=time::$(date +%s)"
#      - uses: actions/checkout@master
#      - name: Install Deps
#        uses: actions/checkout@master
#        with:
#          repository: 'lammps/lammps-testing'
#          ref: 'master'
#          path: 'lammps-testing'
#      - uses: actions/cache@v2
#        with:
#          path: .ccache
#          key: ${{ env.CCACHE_HASH }}-${{ steps.time.outputs.time }}
#          restore-keys: ${{ env.CCACHE_HASH }}
#      - name: Build
#        shell: bash -el {0}
#        run: |
#          ${{ matrix.config.os == 'ubuntu18.04' }} || module load mpi
#          ccache -z
#          lammps-testing/scripts/builds/${{ matrix.config.build }}.sh
#          ccache -s
