name: style
on:
  push:
    branches:
      - master
      - add-style-checks
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ["whitespace", "permissions"]
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyyaml
          sudo apt install -y ninja-build
      - uses: actions/checkout@master
      - name: Configure
        run: cmake -B build -G Ninja -D Python3_EXECUTABLE=$(which python) -S cmake
      - name: "Check ${{ matrix.check }}"
        run: "cmake --build build --target check-${{ matrix.check }}"
